// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package orchestration

import (
	"context"
	"io"
	"rag1/internal/source"
	"rag1/internal/vespa"
	"sync"
)

// Ensure, that ChunkerMock does implement Chunker.
// If this is not the case, regenerate this file with moq.
var _ Chunker = &ChunkerMock{}

// ChunkerMock is a mock implementation of Chunker.
//
//	func TestSomethingThatUsesChunker(t *testing.T) {
//
//		// make and configure a mocked Chunker
//		mockedChunker := &ChunkerMock{
//			ChunkFunc: func(ctx context.Context, reader io.Reader, emit func(index int, chunk string) error) error {
//				panic("mock out the Chunk method")
//			},
//		}
//
//		// use mockedChunker in code that requires Chunker
//		// and then make assertions.
//
//	}
type ChunkerMock struct {
	// ChunkFunc mocks the Chunk method.
	ChunkFunc func(ctx context.Context, reader io.Reader, emit func(index int, chunk string) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Chunk holds details about calls to the Chunk method.
		Chunk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reader is the reader argument value.
			Reader io.Reader
			// Emit is the emit argument value.
			Emit func(index int, chunk string) error
		}
	}
	lockChunk sync.RWMutex
}

// Chunk calls ChunkFunc.
func (mock *ChunkerMock) Chunk(ctx context.Context, reader io.Reader, emit func(index int, chunk string) error) error {
	if mock.ChunkFunc == nil {
		panic("ChunkerMock.ChunkFunc: method is nil but Chunker.Chunk was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Reader io.Reader
		Emit   func(index int, chunk string) error
	}{
		Ctx:    ctx,
		Reader: reader,
		Emit:   emit,
	}
	mock.lockChunk.Lock()
	mock.calls.Chunk = append(mock.calls.Chunk, callInfo)
	mock.lockChunk.Unlock()
	return mock.ChunkFunc(ctx, reader, emit)
}

// ChunkCalls gets all the calls that were made to Chunk.
// Check the length with:
//
//	len(mockedChunker.ChunkCalls())
func (mock *ChunkerMock) ChunkCalls() []struct {
	Ctx    context.Context
	Reader io.Reader
	Emit   func(index int, chunk string) error
} {
	var calls []struct {
		Ctx    context.Context
		Reader io.Reader
		Emit   func(index int, chunk string) error
	}
	mock.lockChunk.RLock()
	calls = mock.calls.Chunk
	mock.lockChunk.RUnlock()
	return calls
}

// Ensure, that EmbedderMock does implement Embedder.
// If this is not the case, regenerate this file with moq.
var _ Embedder = &EmbedderMock{}

// EmbedderMock is a mock implementation of Embedder.
//
//	func TestSomethingThatUsesEmbedder(t *testing.T) {
//
//		// make and configure a mocked Embedder
//		mockedEmbedder := &EmbedderMock{
//			EmbedFunc: func(ctx context.Context, text string) ([]float32, error) {
//				panic("mock out the Embed method")
//			},
//		}
//
//		// use mockedEmbedder in code that requires Embedder
//		// and then make assertions.
//
//	}
type EmbedderMock struct {
	// EmbedFunc mocks the Embed method.
	EmbedFunc func(ctx context.Context, text string) ([]float32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Embed holds details about calls to the Embed method.
		Embed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Text is the text argument value.
			Text string
		}
	}
	lockEmbed sync.RWMutex
}

// Embed calls EmbedFunc.
func (mock *EmbedderMock) Embed(ctx context.Context, text string) ([]float32, error) {
	if mock.EmbedFunc == nil {
		panic("EmbedderMock.EmbedFunc: method is nil but Embedder.Embed was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Text string
	}{
		Ctx:  ctx,
		Text: text,
	}
	mock.lockEmbed.Lock()
	mock.calls.Embed = append(mock.calls.Embed, callInfo)
	mock.lockEmbed.Unlock()
	return mock.EmbedFunc(ctx, text)
}

// EmbedCalls gets all the calls that were made to Embed.
// Check the length with:
//
//	len(mockedEmbedder.EmbedCalls())
func (mock *EmbedderMock) EmbedCalls() []struct {
	Ctx  context.Context
	Text string
} {
	var calls []struct {
		Ctx  context.Context
		Text string
	}
	mock.lockEmbed.RLock()
	calls = mock.calls.Embed
	mock.lockEmbed.RUnlock()
	return calls
}

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			DeleteChunkFunc: func(ctx context.Context, chunkID string) error {
//				panic("mock out the DeleteChunk method")
//			},
//			GetChunkStateFunc: func(ctx context.Context, parentRef string) (map[string]string, error) {
//				panic("mock out the GetChunkState method")
//			},
//			GetSourceStateFunc: func(ctx context.Context, parentID string) (source.SourceState, error) {
//				panic("mock out the GetSourceState method")
//			},
//			UpsertChunkFunc: func(ctx context.Context, chunk vespa.ChunkRecord) error {
//				panic("mock out the UpsertChunk method")
//			},
//			UpsertSourceFunc: func(ctx context.Context, md source.SourceMetadata) (string, string, error) {
//				panic("mock out the UpsertSource method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// DeleteChunkFunc mocks the DeleteChunk method.
	DeleteChunkFunc func(ctx context.Context, chunkID string) error

	// GetChunkStateFunc mocks the GetChunkState method.
	GetChunkStateFunc func(ctx context.Context, parentRef string) (map[string]string, error)

	// GetSourceStateFunc mocks the GetSourceState method.
	GetSourceStateFunc func(ctx context.Context, parentID string) (source.SourceState, error)

	// UpsertChunkFunc mocks the UpsertChunk method.
	UpsertChunkFunc func(ctx context.Context, chunk vespa.ChunkRecord) error

	// UpsertSourceFunc mocks the UpsertSource method.
	UpsertSourceFunc func(ctx context.Context, md source.SourceMetadata) (string, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteChunk holds details about calls to the DeleteChunk method.
		DeleteChunk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChunkID is the chunkID argument value.
			ChunkID string
		}
		// GetChunkState holds details about calls to the GetChunkState method.
		GetChunkState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ParentRef is the parentRef argument value.
			ParentRef string
		}
		// GetSourceState holds details about calls to the GetSourceState method.
		GetSourceState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ParentID is the parentID argument value.
			ParentID string
		}
		// UpsertChunk holds details about calls to the UpsertChunk method.
		UpsertChunk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chunk is the chunk argument value.
			Chunk vespa.ChunkRecord
		}
		// UpsertSource holds details about calls to the UpsertSource method.
		UpsertSource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Md is the md argument value.
			Md source.SourceMetadata
		}
	}
	lockDeleteChunk    sync.RWMutex
	lockGetChunkState  sync.RWMutex
	lockGetSourceState sync.RWMutex
	lockUpsertChunk    sync.RWMutex
	lockUpsertSource   sync.RWMutex
}

// DeleteChunk calls DeleteChunkFunc.
func (mock *RepositoryMock) DeleteChunk(ctx context.Context, chunkID string) error {
	if mock.DeleteChunkFunc == nil {
		panic("RepositoryMock.DeleteChunkFunc: method is nil but Repository.DeleteChunk was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChunkID string
	}{
		Ctx:     ctx,
		ChunkID: chunkID,
	}
	mock.lockDeleteChunk.Lock()
	mock.calls.DeleteChunk = append(mock.calls.DeleteChunk, callInfo)
	mock.lockDeleteChunk.Unlock()
	return mock.DeleteChunkFunc(ctx, chunkID)
}

// DeleteChunkCalls gets all the calls that were made to DeleteChunk.
// Check the length with:
//
//	len(mockedRepository.DeleteChunkCalls())
func (mock *RepositoryMock) DeleteChunkCalls() []struct {
	Ctx     context.Context
	ChunkID string
} {
	var calls []struct {
		Ctx     context.Context
		ChunkID string
	}
	mock.lockDeleteChunk.RLock()
	calls = mock.calls.DeleteChunk
	mock.lockDeleteChunk.RUnlock()
	return calls
}

// GetChunkState calls GetChunkStateFunc.
func (mock *RepositoryMock) GetChunkState(ctx context.Context, parentRef string) (map[string]string, error) {
	if mock.GetChunkStateFunc == nil {
		panic("RepositoryMock.GetChunkStateFunc: method is nil but Repository.GetChunkState was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ParentRef string
	}{
		Ctx:       ctx,
		ParentRef: parentRef,
	}
	mock.lockGetChunkState.Lock()
	mock.calls.GetChunkState = append(mock.calls.GetChunkState, callInfo)
	mock.lockGetChunkState.Unlock()
	return mock.GetChunkStateFunc(ctx, parentRef)
}

// GetChunkStateCalls gets all the calls that were made to GetChunkState.
// Check the length with:
//
//	len(mockedRepository.GetChunkStateCalls())
func (mock *RepositoryMock) GetChunkStateCalls() []struct {
	Ctx       context.Context
	ParentRef string
} {
	var calls []struct {
		Ctx       context.Context
		ParentRef string
	}
	mock.lockGetChunkState.RLock()
	calls = mock.calls.GetChunkState
	mock.lockGetChunkState.RUnlock()
	return calls
}

// GetSourceState calls GetSourceStateFunc.
func (mock *RepositoryMock) GetSourceState(ctx context.Context, parentID string) (source.SourceState, error) {
	if mock.GetSourceStateFunc == nil {
		panic("RepositoryMock.GetSourceStateFunc: method is nil but Repository.GetSourceState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ParentID string
	}{
		Ctx:      ctx,
		ParentID: parentID,
	}
	mock.lockGetSourceState.Lock()
	mock.calls.GetSourceState = append(mock.calls.GetSourceState, callInfo)
	mock.lockGetSourceState.Unlock()
	return mock.GetSourceStateFunc(ctx, parentID)
}

// GetSourceStateCalls gets all the calls that were made to GetSourceState.
// Check the length with:
//
//	len(mockedRepository.GetSourceStateCalls())
func (mock *RepositoryMock) GetSourceStateCalls() []struct {
	Ctx      context.Context
	ParentID string
} {
	var calls []struct {
		Ctx      context.Context
		ParentID string
	}
	mock.lockGetSourceState.RLock()
	calls = mock.calls.GetSourceState
	mock.lockGetSourceState.RUnlock()
	return calls
}

// UpsertChunk calls UpsertChunkFunc.
func (mock *RepositoryMock) UpsertChunk(ctx context.Context, chunk vespa.ChunkRecord) error {
	if mock.UpsertChunkFunc == nil {
		panic("RepositoryMock.UpsertChunkFunc: method is nil but Repository.UpsertChunk was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Chunk vespa.ChunkRecord
	}{
		Ctx:   ctx,
		Chunk: chunk,
	}
	mock.lockUpsertChunk.Lock()
	mock.calls.UpsertChunk = append(mock.calls.UpsertChunk, callInfo)
	mock.lockUpsertChunk.Unlock()
	return mock.UpsertChunkFunc(ctx, chunk)
}

// UpsertChunkCalls gets all the calls that were made to UpsertChunk.
// Check the length with:
//
//	len(mockedRepository.UpsertChunkCalls())
func (mock *RepositoryMock) UpsertChunkCalls() []struct {
	Ctx   context.Context
	Chunk vespa.ChunkRecord
} {
	var calls []struct {
		Ctx   context.Context
		Chunk vespa.ChunkRecord
	}
	mock.lockUpsertChunk.RLock()
	calls = mock.calls.UpsertChunk
	mock.lockUpsertChunk.RUnlock()
	return calls
}

// UpsertSource calls UpsertSourceFunc.
func (mock *RepositoryMock) UpsertSource(ctx context.Context, md source.SourceMetadata) (string, string, error) {
	if mock.UpsertSourceFunc == nil {
		panic("RepositoryMock.UpsertSourceFunc: method is nil but Repository.UpsertSource was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Md  source.SourceMetadata
	}{
		Ctx: ctx,
		Md:  md,
	}
	mock.lockUpsertSource.Lock()
	mock.calls.UpsertSource = append(mock.calls.UpsertSource, callInfo)
	mock.lockUpsertSource.Unlock()
	return mock.UpsertSourceFunc(ctx, md)
}

// UpsertSourceCalls gets all the calls that were made to UpsertSource.
// Check the length with:
//
//	len(mockedRepository.UpsertSourceCalls())
func (mock *RepositoryMock) UpsertSourceCalls() []struct {
	Ctx context.Context
	Md  source.SourceMetadata
} {
	var calls []struct {
		Ctx context.Context
		Md  source.SourceMetadata
	}
	mock.lockUpsertSource.RLock()
	calls = mock.calls.UpsertSource
	mock.lockUpsertSource.RUnlock()
	return calls
}

// Ensure, that SanitizerMock does implement Sanitizer.
// If this is not the case, regenerate this file with moq.
var _ Sanitizer = &SanitizerMock{}

// SanitizerMock is a mock implementation of Sanitizer.
//
//	func TestSomethingThatUsesSanitizer(t *testing.T) {
//
//		// make and configure a mocked Sanitizer
//		mockedSanitizer := &SanitizerMock{
//			CleanFunc: func(text string) string {
//				panic("mock out the Clean method")
//			},
//		}
//
//		// use mockedSanitizer in code that requires Sanitizer
//		// and then make assertions.
//
//	}
type SanitizerMock struct {
	// CleanFunc mocks the Clean method.
	CleanFunc func(text string) string

	// calls tracks calls to the methods.
	calls struct {
		// Clean holds details about calls to the Clean method.
		Clean []struct {
			// Text is the text argument value.
			Text string
		}
	}
	lockClean sync.RWMutex
}

// Clean calls CleanFunc.
func (mock *SanitizerMock) Clean(text string) string {
	if mock.CleanFunc == nil {
		panic("SanitizerMock.CleanFunc: method is nil but Sanitizer.Clean was just called")
	}
	callInfo := struct {
		Text string
	}{
		Text: text,
	}
	mock.lockClean.Lock()
	mock.calls.Clean = append(mock.calls.Clean, callInfo)
	mock.lockClean.Unlock()
	return mock.CleanFunc(text)
}

// CleanCalls gets all the calls that were made to Clean.
// Check the length with:
//
//	len(mockedSanitizer.CleanCalls())
func (mock *SanitizerMock) CleanCalls() []struct {
	Text string
} {
	var calls []struct {
		Text string
	}
	mock.lockClean.RLock()
	calls = mock.calls.Clean
	mock.lockClean.RUnlock()
	return calls
}
